### ISSUE TITLE
Error reading addIndirect

### ISSUE THREAD

**Issue by anisus** [mucklet/mucklet-client#9]
## Issue

An error occasionally occurs in the browser console:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'addIndirect')
    at u._prepareValue (ResClient.js:1336:10)
    at u._handleAddEvent (ResClient.js:641:16)
    at _patchDiff._handleRemoveEvent.idx (ResClient.js:1124:25)
    at u._patchDiff (ResClient.js:1215:4)
    at u._syncCollection (ResClient.js:1122:8)
    at u._syncItems (ResClient.js:1105:9)
    at ResClient.js:1048:35
    at Array.forEach (<anonymous>)
    at u._cacheResources (ResClient.js:1048:17)
    at u._handleAddEvent (ResClient.js:640:8)
```

While this bug probably lies in [resclient](https://github.com/resgateio/resclient), it does break the game when it happens.

Help is needed to find out how to replicate the issue!

## Notes

* It has occurred when waking up a character on another device while having the client running in the browser.

**Comment by anisus** [comment]
Likely caused by this Resgate bug:

https://github.com/resgateio/resgate/issues/241

Fixed in Resgate v1.8.0, and not related to client.
