### ISSUE TITLE
Error request new area owner

### ISSUE THREAD

**Issue by anisus** [mucklet/mucklet-client#94]
## Issue

When making a request for a new area owner using a non-builder account, clicking the "Make request" button for the DialogSetAreaOwner module will result in an error:

```text
DialogSetAreaOwner.js:149 Uncaught TypeError: Cannot read properties of undefined (reading 'requestAreaOwner')
    at eval (DialogSetAreaOwner.js:149:63)
    at click (Confirm.js:60:26)
    at Elem.eval (Elem.js:724:1)
```

See the discussion on Wolfery Forum:
https://forum.wolfery.com/t/bug-giving-areas-to-other-players-not-working/2083

**Comment by anisus** [comment]
Resolved in PR #95
